version: '3.6'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.enforce.bootstrap.checks=true"
    ulimits:
      nproc: 262144
      memlock:
          soft: -1
          hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - default

  web:
    build: ./web
    volumes:
      - ./web:/usr/share/web
    working_dir: /usr/share/web
    restart: always
    ports:
      - "8080:5000"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - default

networks:
  default: